generalInformation:
  serviceAdminEmail: a
  gheUsername: kkanto
  billingAccount: a
  billingTeamName: a
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
  projectKey: a
  projectName: a
  leadUsername: a
  documentationUrl: a
projectInformation:
  projectName: adfasdasskdsa2222
  projectShortName: dosakdoaksssdoa2222
  buildType: maven
  testInstance: false
  preprodInstance: false
  uatInstance: false
cloudService:
  awsOrAzure: aks
  deploymentLocation: azure_we1
automationService:
  jenkinsOrGithubActions: jenkins
  jenkinsAdmin: a
  jenkinsDeveloper: a
  jenkinsKubernetesAccess: a
  kvUserOrGroupName: a
  nexusKubernetesAccess: a
gheOrganization:
  organizationName: kkanto
  isNew: false
testingTools:
  sonarQube: false
  adminGroup: ""
  kubernetesAccess: ""
